name: ci
on: push
env: 
  test-art-name: testReport
  test-art-files: ./reports/*
jobs:
    unittesting:
        runs-on: ubuntu-latest
        env:
          nodejsver: '18.0'  
        steps:
          - name: checkout the Project 
            uses: actions/checkout@v4
          - name: Step up Nodejs 
            uses: actions/setup-node@v4
            with:
                node-version: ${{env.nodejsver}}
          - name: install Dependencies 
            run: npm install nyc
          - name: Unit Test the project 
            run: npm test 
          - name: find the files 
            run: mv reports/awesome-reports/mochawesome.html mochawesome.html
          - name: Upload the Test Report 
            uses: actions/upload-artifact@v4
            with:
                name: test-art-name
                path: $test-art-files
        